PKG_NAME := blinky

bins := blinky

blinky_sources := blinky.c

blinky_cflags := -I/home/ravitejareddy/Desktop/espressif/esp-open-sdk/sdk/include 

blinky_ldflags := -L/home/ravitejareddy/Desktop/espressif/esp-open-sdk/sdk/lib

.PHONY: flash

include make.inc
