Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.synced_folder "../", "/home/vagrant/switch-case"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
    # vb.customize ['modifyvm', :id, '--usb', 'on']
    # vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'USB_to_TTL_converter', '--vendorid', 0x10c4, '--productid', '0xea60']
  end

end
