bins := mqtt

mqtt_sources := mqtt.c
mqtt_cflags := -I../../libs/esp_mqtt/include -I../../libs/esp_mqtt/mqtt/include -I../../libs/esp_mqtt/modules/include
mqtt_ldflags := -lssl -lmqtt

include make.inc
